# Generated by Django 3.2.5 on 2021-07-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TeamInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("franchise", models.CharField(max_length=60)),
                ("league", models.CharField(max_length=30)),
                ("year_established", models.IntegerField()),
                ("years_in_operation", models.IntegerField()),
                ("games_played", models.IntegerField(null=True)),
                ("wins", models.IntegerField(null=True)),
                ("losses", models.IntegerField(null=True)),
                ("ties", models.IntegerField(null=True)),
                ("ot_losses", models.IntegerField(null=True)),
                ("points", models.IntegerField(null=True)),
                ("points_percentage", models.CharField(max_length=10, null=True)),
                ("playoff_years", models.IntegerField(null=True)),
                ("division_wins", models.IntegerField(null=True)),
                ("conference_wins", models.IntegerField(null=True)),
                ("stanley_cups_won", models.IntegerField(null=True)),
                ("logo_image_link", models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
